#!/bin/bash
install() {
	install_nvim
	install_nvim_config
	install_nvim_plugin_manager
}
install_nvim() {
	curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
	vim=/usr/bin/vim
	sudo mv nvim.appimage $vim
	sudo chown root:root $vim
	sudo chmod a+rx $vim
}

install_nvim_config() {
	mkdir -p ~/.config/nvim/plug-config
	cp nvimconfig/init.vim ~/.config/nvim/init.vim
	cp nvimconfig/plug-config/* ~/.config/nvim/plug-config/
	vim +'PlugInstall --sync' +qa
}

install_nvim_plugin_manager() {
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim \
	--create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

$@
