#!/bin/bash
install() {
	install_nvim
	install_nvim_config
	install_nvim_plugin_manager
}
install_nvim() {
	curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
	vim=/usr/bin/vim
	chmod a+rx nvim.appimage
	sudo mv nvim.appimage $vim
}

install_nvim_config() {
	mkdir -p ~/.config/nvim
	cp nvimconfig/init.vim ~/.config/nvim/init.vim
}

install_nvim_plugin_manager() {
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim \
	--create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

install_zig_lsp() {
	git clone --recurse-submodules https://github.com/zigtools/zls
	cd zls
	zig build -Drelease-safe
	./zig-cache/bin/zls config
	cp ./zls/zig-cache/bin/zls ~/.develop/bin
}

$@
