#!/usr/bin/python3
import sys
import pathlib
import shutil
import os
import xml.dom.minidom
import shutil
import subprocess
from distutils.dir_util import copy_tree

backup_dir = ""
user_path = ""

def setup_directories():
    folders = ["thunar", "xfce-settings", "themes", "icons", "backgrounds"]
    for folder in folders:
        pathlib.Path( f'{backup_dir}/{folder}' ).mkdir( parents=True, exist_ok=True )

def backup():
    copy_tree(f"{user_path}/.config/Thunar/", f"{backup_dir}/thunar/")
    copy_tree(f"{user_path}/.config/xfce4/", f"{backup_dir}/xfce-settings/")

    settings_xml = f"{backup_dir}/xfce-settings/xfconf/xfce-perchannel-xml/xsettings.xml"
    icon_theme_name = get_xml_property_value(settings_xml, "IconThemeName")
    theme_name = get_xml_property_value(settings_xml, "ThemeName")

    backup_theme("icons", icon_theme_name)
    backup_theme("themes", theme_name)

    backup_background()

    handle_whisker()

    subprocess.run(f"tar -czf {backup_dir}.tar.gz {backup_dir}".split())

def backup_theme(folder: str, theme_pack: str):
    if pathlib.Path(f"/usr/share/{folder}/{theme_pack}").exists():
        theme_dir = f"/usr/share/{folder}"
    else:
        theme_dir = f"{user_path}/.{folder}"

    origin_theme = theme_pack.split("-")[0]
    if pathlib.Path(f"{theme_dir}/{origin_theme}").exists():
        copy_tree(f"{theme_dir}/{origin_theme}/", f"{backup_dir}/{folder}/{origin_theme}")
    copy_tree(f"{theme_dir}/{theme_pack}/", f"{backup_dir}/{folder}/{theme_pack}")

def backup_background():
    image_properties = ["image-path", "last-image", "last-single-image"]
    xfce_desktop_xml = f'{backup_dir}/xfce-settings/xfconf/xfce-perchannel-xml/xfce4-desktop.xml'
    dom = xml.dom.minidom.parse(xfce_desktop_xml)
    for xml_property in dom.getElementsByTagName('property'):
        if xml_property.getAttribute("name") in image_properties:
            image_path = xml_property.getAttribute("value")
            image_name = image_path.split('/')[-1]
            shutil.copy(image_path, f"{backup_dir}/backgrounds/{image_name}")
            xml_property.setAttribute("value", f"~/.backgrounds/{image_name}")
    with open(xfce_desktop_xml,"w") as xml_handle:
        dom.writexml(xml_handle)

def restore():
    subprocess.run(f"tar -xzf {backup_dir}.tar.gz".split())
    
    copy_tree(f"{backup_dir}/xfce-settings", f"{user_path}/.config/xfce4")
    copy_tree(f"{backup_dir}/thunar", f"{user_path}/.config/Thunar")
    copy_tree(f"{backup_dir}/icons", f"{user_path}/.icons")
    copy_tree(f"{backup_dir}/themes", f"{user_path}/.themes")
    copy_tree(f"{backup_dir}/backgrounds", f"{user_path}/.backgrounds")

def handle_whisker():
    files = pathlib.Path(f'{backup_dir}/xfce-settings/panel').glob('**/*')
    for FILE in files:
        FILE = str(FILE)
        with open(FILE) as f:
            for line in f:
                if "button-icon" in line:
                    shutil.copy(line.strip().split("=")[-1], f"{user_path}/.icons")
                    break
            break
    replace_in_file(FILE, '/usr/share/icons', '~/.icons')

def replace_in_file(FILE: str, search: str, replace: str):
    with open(FILE, 'r') as file:
        filedata = file.read()

    with open(FILE, 'w') as file:
        filedata = filedata.replace(search, replace)
        file.write(filedata)

def get_xml_property_value(xml_file: str, xml_property_name: str) -> str:
    dom = xml.dom.minidom.parse(xml_file)
    properties = dom.getElementsByTagName('property')
    for xml_property in properties:
        if xml_property.getAttribute("name") == xml_property_name:
            return xml_property.getAttribute("value")

#def copy_tree(src: str, dest: str):
#    shutil.copytree(src, dest, symlinks=True, dirs_exist_ok=True)

if __name__ == "__main__":
    if len(sys.argv) == 3:
        backup_dir = sys.argv[2];
        user_path = os.path.expanduser('~')
        if sys.argv[1] == "backup":
            setup_directories()
            backup()
        elif sys.argv[1] == "restore":
            restore()
        else:
            print("invalid")
    else:
        print("invalid")